name: Azure Static Web Apps CI/CD (2-step)

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

env:
  APP_LOCATION: "/"           # Ruta raíz del código fuente
  OUTPUT_LOCATION: "dist"     # Carpeta generada por Vite

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Static Web App
    outputs:
      output-path: ${{ steps.set-output.outputs.output-path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Set output path
        id: set-output
        run: echo "output-path=${{ env.OUTPUT_LOCATION }}" >> $GITHUB_OUTPUT

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-app
          path: ${{ env.OUTPUT_LOCATION }}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Azure Static Web Apps
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: static-app
          path: ${{ env.OUTPUT_LOCATION }}

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_PLANT_05E55B21E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}
